"""Trace the VarsitySoko V-mark silhouette into a clip-path polygon.

Emits two point lists of equal length, anchored at matching features so a
rectangle can be tweened into the mark without points crossing over:

  MARK_SHAPE  points normalised to the artwork frame (0..1), so they line up
              with an <img> of mark.svg laid out at the same aspect ratio
  MARK_RECT   the same count of points walked clockwise around a full rect

Run: python3 scripts/extract-mark-outline.py
"""

from PIL import Image

SRC = "public/images/mark.png"
OUT = "components/Hero/markOutline.ts"
ALPHA_CUTOFF = 140  # ignores the traced drop shadow
SAMPLES_PER_EDGE = 12


def spans(row, cutoff):
    """Contiguous runs of opaque pixels in one scanline."""
    runs, start = [], None
    for x, a in enumerate(row):
        if a >= cutoff and start is None:
            start = x
        elif a < cutoff and start is not None:
            runs.append((start, x - 1))
            start = None
    if start is not None:
        runs.append((start, len(row) - 1))
    return [r for r in runs if r[1] - r[0] > 2]


def resample(chain, n):
    """Even arc-length resample of a polyline, endpoints preserved."""
    if len(chain) < 2:
        return [chain[0]] * n
    dists = [0.0]
    for (x0, y0), (x1, y1) in zip(chain, chain[1:]):
        dists.append(dists[-1] + ((x1 - x0) ** 2 + (y1 - y0) ** 2) ** 0.5)
    total = dists[-1]
    out, j = [], 0
    for i in range(n):
        target = total * i / (n - 1)
        while j < len(dists) - 2 and dists[j + 1] < target:
            j += 1
        seg = dists[j + 1] - dists[j]
        t = 0.0 if seg == 0 else (target - dists[j]) / seg
        x0, y0 = chain[j]
        x1, y1 = chain[j + 1]
        out.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t))
    return out


def main():
    img = Image.open(SRC).convert("RGBA")
    alpha = img.getchannel("A")
    w, h = img.size
    px = list(alpha.getdata())
    rows = [px[y * w:(y + 1) * w] for y in range(h)]

    row_spans = [spans(r, ALPHA_CUTOFF) for r in rows]
    ys = [y for y, s in enumerate(row_spans) if s]
    top, bottom = ys[0], ys[-1]

    xs = [x for y in ys for s in row_spans[y] for x in s]
    left, right = min(xs), max(xs)

    # The notch is the last row scanning down that still shows two arms.
    notch_y = top
    for y in range(top, bottom + 1):
        if len(row_spans[y]) >= 2:
            notch_y = y

    outer_left, outer_right, inner_left, inner_right = [], [], [], []
    for y in range(top, bottom + 1):
        s = row_spans[y]
        if not s:
            continue
        outer_left.append((s[0][0], y))
        outer_right.append((s[-1][1], y))
        if len(s) >= 2:
            inner_left.append((s[0][1], y))
            inner_right.append((s[-1][0], y))

    notch_x = (inner_left[-1][0] + inner_right[-1][0]) / 2 if inner_left else (left + right) / 2
    inner_left.append((notch_x, notch_y))
    inner_right.append((notch_x, notch_y))

    bottom_span = row_spans[bottom]
    bottom_left = (bottom_span[0][0], bottom)
    bottom_right = (bottom_span[-1][1], bottom)

    # Clockwise from the mark's outer top-left corner. Each traced edge is
    # paired with the rectangle segment it unfolds from, so the tween keeps
    # every point on its own edge instead of letting them cross over.
    edges = [
        # traced edge                                    rect start   rect end
        ([outer_left[0], inner_left[0]],                  (0.00, 0.0), (0.25, 0.0)),
        (resample(inner_left, SAMPLES_PER_EDGE),          (0.25, 0.0), (0.50, 0.0)),
        (resample(inner_right[::-1], SAMPLES_PER_EDGE),   (0.50, 0.0), (0.75, 0.0)),
        ([inner_right[0], outer_right[0]],                (0.75, 0.0), (1.00, 0.0)),
        (resample(outer_right, SAMPLES_PER_EDGE),         (1.00, 0.0), (1.00, 1.0)),
        ([bottom_right, bottom_left],                     (1.00, 1.0), (0.00, 1.0)),
        (resample(outer_left[::-1], SAMPLES_PER_EDGE),    (0.00, 1.0), (0.00, 0.0)),
    ]

    shape, rect, seen = [], [], set()

    for points, (rx0, ry0), (rx1, ry1) in edges:
        for i, (x, y) in enumerate(points):
            key = (round(x, 1), round(y, 1))
            if key in seen:
                continue
            seen.add(key)
            t = i / (len(points) - 1) if len(points) > 1 else 0.0
            shape.append((x / w, y / h))
            rect.append((rx0 + (rx1 - rx0) * t, ry0 + (ry1 - ry0) * t))

    norm = shape

    def fmt(points):
        return ",\n".join(f"  [{x:.4f}, {y:.4f}]" for x, y in points)

    with open(OUT, "w") as f:
        f.write(
            "// Generated by scripts/extract-mark-outline.py from public/images/mark.png.\n"
            "// Do not hand-edit — re-run the script if the mark artwork changes.\n\n"
            "export type Point = readonly [number, number];\n\n"
            "/** V-mark silhouette as fractions of the artwork frame. */\n"
            f"export const MARK_SHAPE: Point[] = [\n{fmt(norm)},\n];\n\n"
            "/** Matching clockwise walk around a full rectangle, for the tween. */\n"
            f"export const MARK_RECT: Point[] = [\n{fmt(rect)},\n];\n\n"
            "/** Aspect ratio (w/h) of the artwork frame. */\n"
            f"export const MARK_ASPECT = {w / h:.4f};\n"
        )

    print(
        f"{len(norm)} points · frame {w}x{h} (aspect {w / h:.4f}) · "
        f"art {right - left}x{bottom - top} · notch at y={notch_y / h:.3f} -> {OUT}"
    )


if __name__ == "__main__":
    main()
